server:
    port : 8081
spring:
    datasource:
        url: jdbc:postgresql://181.94.220.137:5433/test
       # url: jdbc:postgresql://192.168.0.201:5432/libertyaAsu
        username: libertya
        password: libertya
        driver-class-name: org.postgresql.Driver
jwt:
    secret: yourSecretKeyHere
    expiration: 3600000 # Set the expiration time in milliseconds (e.g., 1 hour)
